### ISSUE TITLE
Sleep between visiting website?

### ISSUE THREAD

**Issue by mikelam14** [BiermanM/job_scraper#1]
Hi there, just wondering if there is any mechanism to prevent hitting the company server too often causing IP being blocked? If so could you point that out? Thank you a lot.

**Comment by BiermanM** [comment]
Hi Mike! That would depend on how often the user runs the program; this scraper is designed to only to visit a given company's website once. For the companies not using Lever or Greenhouse, specifically ones that have multiple pages, it waits until a page fully loads before scraping it. If you run the scraper, you can see that for scraping Apple's job board, it actually opens a browser and navigates through the pages, simulating what an actual user would do. Since it's simulating movements of an actual user (i.e. visiting the pages within a job board sequentially instead of loading all pages at once), it's very unlikely that a given IP will be blocked.
